"""
input/base.py - THE CONTRACT.

Everything to the left of ChordEvent is replaceable (webcam today, VR tomorrow).
Everything to the right of it never changes.

Do not edit this file after day one without telling your teammate.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Optional, Tuple


@dataclass
class Hand:
    landmarks: List[Tuple[float, float, float]]  # 21 (x, y, z), normalised 0-1
    handedness: str                              # "Left" or "Right"
    confidence: float = 1.0

    def point(self, idx: int) -> Tuple[float, float, float]:
        return self.landmarks[idx]


@dataclass
class InputFrame:
    timestamp: float                  # seconds, monotonic
    left: Optional[Hand] = None       # None when that hand is not visible
    right: Optional[Hand] = None
    raw_image: object = None          # BGR ndarray, debug overlay only


@dataclass
class ChordEvent:
    chord: str          # "A", "D", "E", "G", "C"
    strum: str          # "DOWN" or "UP"
    strength: float     # 0..1, from strum velocity
    timestamp: float


class InputSource(ABC):
    """Any device that can produce hand poses implements this. That is the
    whole VR story: vr_source.py fills in these two methods and nothing
    else in the project changes."""

    name = "base"

    @abstractmethod
    def read(self) -> Optional[InputFrame]:
        """Return the newest frame, or None if nothing is available yet."""

    @abstractmethod
    def release(self) -> None:
        """Free the camera / device."""

    # Optional: sources that generate events directly (keyboard, VR controllers)
    # override this instead of going through the gesture recogniser.
    def poll_events(self) -> List[ChordEvent]:
        return []


# MediaPipe landmark indices, named so the gesture code reads like English.
WRIST = 0
THUMB_TIP, THUMB_IP, THUMB_MCP = 4, 3, 2
INDEX_TIP, INDEX_PIP, INDEX_MCP = 8, 6, 5
MIDDLE_TIP, MIDDLE_PIP, MIDDLE_MCP = 12, 10, 9
RING_TIP, RING_PIP, RING_MCP = 16, 14, 13
PINKY_TIP, PINKY_PIP, PINKY_MCP = 20, 18, 17
